### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by zwlvd** [lty2226262/Car_studio#1]
I notice the outstanding work of Car-Studio. I wonder when the whole code will be released. I can't wait to take a try.

**Comment by AmazingRoad** [comment]
@lty2226262 I help you to @ him

**Comment by lty2226262** [comment]
Thank you for your interest in our work. We appreciate your support. Our paper is currently undergoing the review process, and we are eagerly awaiting the feedback from the reviewers. Once we have incorporated the reviewers' comments and finalized the camera-ready version, we will proceed with the release. The timeline for publication depends on the reviewing time, but we assure you that it will not exceed six months. We will keep you updated on the progress and provide you with the latest information regarding our release. Thank you for your understanding and patience during this review period.

**Comment by AlanLiangC** [comment]
HI, Same question: "I notice the outstanding work of Car-Studio. I wonder when the whole code will be released. I can't wait to take a try."

**Comment by lty2226262** [comment]
Thank you for your patience. We are delighted to announce that the codes have been officially released.
