### ISSUE TITLE
How to obtain visual results

### ISSUE THREAD

**Issue by Starak-x** [lty2226262/Car_studio#4]
Thank you for you excellent work, which inspired me a lot. But I do not know how to obtain visual results or how to render in single-view supervision for zero-shot learning, multi-view supervision for novel scene synthesis, and patch reconstruction with test-time optimization  setting.
When I use the "ns-viewer", the following error will occur,
![image](https://github.com/lty2226262/Car_studio/assets/71073947/5da561ac-7e1a-41dd-ae6d-191b07cff46c)

**Comment by lty2226262** [comment]
You can directly view the visualization results on wandb. Alternatively, you can refer to the 'car_studio/scripts/datasets/render_novel_view.py' scripts to create your own custom visualization scripts.
