### ISSUE TITLE
provide train config

### ISSUE THREAD

**Issue by qaqaqaaaa** [lty2226262/Car_studio#6]
author ;)
could you provide the train configs in paper(mainly MethodSpecification)

**Comment by qaqaqaaaa** [comment]
I set 3072 rays  in pixel sampler，When I train, there will be an error reported halfway through.

**Comment by lty2226262** [comment]
Thank you for your interest in our work. Could you kindly provide additional details regarding the error you encountered?

**Comment by qaqaqaaaa** [comment]
I think I slove this problem，I want to ask another problem, when I try render_novel_view.py, the _get_one_car_translation function . results that seems during the trans process，the white car will change color， how to solve it
